modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "The MIT License (MIT)"

[[mixin]]
mixin = "tfc_modular.mixins.json"

[[mods]]
modId = "tfc_modular"
version = "${version}"
displayName = "TFC Modular"
authors = "Coach_mdl"
description = '''
Bring your Terrafirmacraft tools to life!
'''
logoFile = "assets/tfc_modular/textures/logo.png"

[[dependencies.tfc_modular]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tfc_modular]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tfc_modular]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tfc_modular]]
modId="tfc"
mandatory=true
versionRange="[1.20.1-3.2.19,)"
ordering="AFTER"
side="BOTH"

[[dependencies.tfc_modular]]
modId = "miapi"
mandatory = true
ordering = "AFTER"
versionRange = "[1.1.48,)"
side = "BOTH"

[[dependencies.tfc_modular]]
modId="tm_arsenal"
mandatory=true
versionRange="[forge-1.12-1.20.1,)"
ordering="AFTER"
side="BOTH"